version: '3.7'

services:
  alpine:
    container_name: alpine-cron
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    environment:
      - CUSTOM_ENV_VAR=foobar
    volumes:
      - ./alpine-crontab-example.txt:/var/spool/cron/crontabs/root
